spring:
  application:
    name: spring-boot-sample
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sample;
    username: sa
    password: sa
  h2:
    console:
      enabled: true

doma:
  dialect: h2